openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - name: Projects
  - name: Project Bids
  - name: Talent Bids
  - name: Talents
paths:
  /v1/talents/{talentId}:
    get:
      tags:
        - Talents
      description: Get a Talent by Id
      operationId: getTalent
      parameters:
        - name: talentId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TalentModel'
    put:
      tags:
        - Talents
      description: Update a Talent
      operationId: updateTalent
      parameters:
        - name: talentId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TalentModel'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TalentModel'
    delete:
      tags:
        - Talents
      description: Delete a Talent
      operationId: deleteTalent
      parameters:
        - name: talentId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: boolean
  /v1/projects/{projectId}:
    get:
      tags:
        - Projects
      description: Get a Project by Id
      operationId: getProject
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProjectModel'
    put:
      tags:
        - Projects
      description: Update a Project
      operationId: updateProject
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectModel'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProjectModel'
    delete:
      tags:
        - Projects
      description: Delete a Project
      operationId: deleteProject
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: boolean
  /v1/talents:
    get:
      tags:
        - Talents
      description: Get all Talents
      operationId: getTalents
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TalentModel'
    post:
      tags:
        - Talents
      description: Create a new Talent
      operationId: createTalent
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TalentModel'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TalentModel'
  /v1/talents/{talentId}/bids:
    get:
      tags:
        - Talent Bids
      description: Get the Bids for the Talent
      operationId: getBidsByTalent
      parameters:
        - name: talentId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BidModel'
    post:
      tags:
        - Talent Bids
      description: Create a Bid for a Project
      operationId: createBid
      parameters:
        - name: talentId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BidModel'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BidModel'
  /v1/projects:
    get:
      tags:
        - Projects
      description: Get all Projects
      operationId: getProjects
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectModel'
    post:
      tags:
        - Projects
      description: Create a new Project
      operationId: createProject
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectModel'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProjectModel'
  /v1/projects/{projectId}/bids:
    get:
      tags:
        - Project Bids
      description: Get the Bids for the Project
      operationId: getBidsByProject
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BidModel'
components:
  schemas:
    TalentModel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        address:
          type: string
        city:
          type: string
        state:
          type: string
        zipCode:
          type: string
        email:
          type: string
        title:
          type: string
        salary:
          type: number
          format: double
        status:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    ProjectModel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        description:
          type: string
        company:
          type: string
        budget:
          type: number
          format: double
        address:
          type: string
        city:
          type: string
        state:
          type: string
        zipCode:
          type: string
        status:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    BidModel:
      type: object
      properties:
        talent:
          $ref: '#/components/schemas/TalentModel'
        project:
          $ref: '#/components/schemas/ProjectModel'
        status:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
